---
# ansible-playbook -i ../../common/XXX/hosts mysql.yml -u YYY -v 
# XXX: dev,test,prod
# YYY: remote user login name

#########################
# CIS Hardening         #
#########################

- hosts: dbservers
  sudo: true
  tags: cis
  roles:
    - ansible-cis

#########################
# MySQL                 #
#########################

- hosts: dbservers
  sudo: true
  tags: mysql
  roles:
    - role: mysql
    
#########################
# OSSEC Client          #
#########################

- hosts: dbservers
  sudo: true
  tags: ossec
  roles:
    - ansible-ossec-agent